theme: jekyll-theme-minimal
logo:  figs/logo.png
twitter_username: e__soriano
description: "hacklab0x2"
baseurl: ""
url: https://sysfatal.github.io/hacklab0x2
title_image: https://sysfatal.github.io/hacklab0x2/figs/logo.png
twitter:
  username: e__soriano
  card: "summary"
